import type { User } from './types';

export const mockUsers: User[] = [
  {
    id: 1,
    name: 'Alice Johnson',
    initials: 'AJ',
    realm: ['Professional', 'Social'],
    position: { x: 32.08, y: -81.09 },
    avatar: 'https://picsum.photos/seed/user1/200/200',
    profile: 'Lead Software Engineer at TechCorp. Passionate about AI and building scalable systems. Looking to connect with other tech professionals.',
  },
  {
    id: 2,
    name: 'Bob Williams',
    initials: 'BW',
    realm: ['Social', 'Dating'],
    position: { x: 32.07, y: -81.10 },
    avatar: 'https://picsum.photos/seed/user2/200/200',
    profile: 'Loves hiking, trying new coffee shops, and live music. Seeking a partner for adventures and quiet moments.',
  },
  {
    id: 3,
    name: 'Charlie Brown',
    initials: 'CB',
    realm: ['Dating'],
    position: { x: 32.085, y: -81.08 },
    avatar: 'https://picsum.photos/seed/user3/200/200',
    profile: 'Graphic designer with a love for art museums and vintage films. Searching for a meaningful connection with someone creative and kind.',
  },
  {
    id: 4,
    name: 'Diana Prince',
    initials: 'DP',
    realm: ['Hook Up', 'Party/Etc'],
    position: { x: 32.075, y: -81.095 },
    avatar: 'https://picsum.photos/seed/user4/200/200',
    profile: 'Here for a good time, not a long time. Into spontaneous nights out and exploring the city\'s nightlife. Discretion and mutual respect are key.',
  },
  {
    id: 5,
    name: 'Ethan Hunt',
    initials: 'EH',
    realm: ['Party/Etc'],
    position: { x: 32.09, y: -81.11 },
    avatar: 'https://picsum.photos/seed/user5/200/200',
    profile: 'Host of exclusive themed parties. Looking for open-minded individuals to join our vibrant community. Experience and consent are paramount.',
  },
  {
    id: 6,
    name: 'Fiona Glenanne',
    initials: 'FG',
    realm: ['Social', 'Party/Etc'],
    position: { x: 32.06, y: -81.08 },
    avatar: 'https://picsum.photos/seed/user6/200/200',
    profile: 'Adrenaline junkie and event organizer. If it involves music, dancing, or adventure, I\'m in. Let\'s make some memories.',
  },
  {
    id: 7,
    name: 'George Costanza',
    initials: 'GC',
    realm: ['Professional'],
    position: { x: 32.082, y: -81.085 },
    avatar: 'https://picsum.photos/seed/user7/200/200',
    profile: 'Vandelay Industries. Architect. Interested in urban planning and sustainable design. Let\'s discuss potential collaborations.',
  },
  {
    id: 8,
    name: 'Hannah Montana',
    initials: 'HM',
    realm: ['Dating', 'Social'],
    position: { x: 32.078, y: -81.092 },
    avatar: 'https://picsum.photos/seed/user8/200/200',
    profile: 'Living the best of both worlds. I enjoy quiet evenings reading and exciting weekends exploring. Looking for someone who can keep up.',
  },
  {
    id: 9,
    name: 'Ian Malcolm',
    initials: 'IM',
    realm: ['Hook Up'],
    position: { x: 32.065, y: -81.105 },
    avatar: 'https://picsum.photos/seed/user9/200/200',
    profile: 'Chaos theorist. Life, uh, finds a way. Open to casual, intelligent, and thrilling encounters.',
  },
  {
    id: 10,
    name: 'Jackie Brown',
    initials: 'JB',
    realm: ['Party/Etc'],
    position: { x: 32.095, y: -81.07 },
    avatar: 'https://picsum.photos/seed/user10/200/200',
    profile: 'Into the alternative and kink scene. Experienced and looking for like-minded people for events and private gatherings. Respect and communication are everything.',
  },
  {
    id: 11,
    name: 'Kevin McCallister',
    initials: 'KM',
    realm: ['Social'],
    position: { x: 32.077, y: -81.088 },
    avatar: 'https://picsum.photos/seed/user11/200/200',
    profile: 'Good at being resourceful and planning. Looking for a group for board game nights or escape rooms.',
  },
  {
    id: 12,
    name: 'Laura Palmer',
    initials: 'LP',
    realm: ['Hook Up', 'Dating'],
    position: { x: 32.088, y: -81.098 },
    avatar: 'https://picsum.photos/seed/user12/200/200',
    profile: 'Sometimes my arms bend back. Enigmatic and looking for a deep, possibly dangerous, connection. Not everything is as it seems.',
  },
];
